"""Static list of French departments with approximate centroid coordinates."""

DEPARTMENTS = [
    {"code": "01", "name": "Ain", "region": "Auvergne-Rhône-Alpes", "lat": 46.0833, "lon": 5.3333},
    {"code": "02", "name": "Aisne", "region": "Hauts-de-France", "lat": 49.5, "lon": 3.5},
    {"code": "03", "name": "Allier", "region": "Auvergne-Rhône-Alpes", "lat": 46.3333, "lon": 3.25},
    {"code": "04", "name": "Alpes-de-Haute-Provence", "region": "Provence-Alpes-Côte d'Azur", "lat": 44.0833, "lon": 6.2333},
    {"code": "05", "name": "Hautes-Alpes", "region": "Provence-Alpes-Côte d'Azur", "lat": 44.6667, "lon": 6.3333},
    {"code": "06", "name": "Alpes-Maritimes", "region": "Provence-Alpes-Côte d'Azur", "lat": 43.9167, "lon": 7.1667},
    {"code": "07", "name": "Ardèche", "region": "Auvergne-Rhône-Alpes", "lat": 44.75, "lon": 4.5},
    {"code": "08", "name": "Ardennes", "region": "Grand Est", "lat": 49.6667, "lon": 4.6667},
    {"code": "09", "name": "Ariège", "region": "Occitanie", "lat": 42.95, "lon": 1.5333},
    {"code": "10", "name": "Aube", "region": "Grand Est", "lat": 48.3333, "lon": 4.0833},
    {"code": "11", "name": "Aude", "region": "Occitanie", "lat": 43.0833, "lon": 2.5},
    {"code": "12", "name": "Aveyron", "region": "Occitanie", "lat": 44.3167, "lon": 2.55},
    {"code": "13", "name": "Bouches-du-Rhône", "region": "Provence-Alpes-Côte d'Azur", "lat": 43.5, "lon": 5.0},
    {"code": "14", "name": "Calvados", "region": "Normandie", "lat": 49.0833, "lon": -0.25},
    {"code": "15", "name": "Cantal", "region": "Auvergne-Rhône-Alpes", "lat": 45.0, "lon": 2.6667},
    {"code": "16", "name": "Charente", "region": "Nouvelle-Aquitaine", "lat": 45.6667, "lon": 0.25},
    {"code": "17", "name": "Charente-Maritime", "region": "Nouvelle-Aquitaine", "lat": 45.75, "lon": -0.75},
    {"code": "18", "name": "Cher", "region": "Centre-Val de Loire", "lat": 47.0833, "lon": 2.5},
    {"code": "19", "name": "Corrèze", "region": "Nouvelle-Aquitaine", "lat": 45.3, "lon": 1.8},
    {"code": "2A", "name": "Corse-du-Sud", "region": "Corse", "lat": 41.9167, "lon": 8.75},
    {"code": "2B", "name": "Haute-Corse", "region": "Corse", "lat": 42.5, "lon": 9.0},
    {"code": "21", "name": "Côte-d'Or", "region": "Bourgogne-Franche-Comté", "lat": 47.5, "lon": 4.8333},
    {"code": "22", "name": "Côtes-d'Armor", "region": "Bretagne", "lat": 48.5, "lon": -3.25},
    {"code": "23", "name": "Creuse", "region": "Nouvelle-Aquitaine", "lat": 46.0833, "lon": 1.9},
    {"code": "24", "name": "Dordogne", "region": "Nouvelle-Aquitaine", "lat": 45.1833, "lon": 0.75},
    {"code": "25", "name": "Doubs", "region": "Bourgogne-Franche-Comté", "lat": 47.25, "lon": 6.25},
    {"code": "26", "name": "Drôme", "region": "Auvergne-Rhône-Alpes", "lat": 44.75, "lon": 5.25},
    {"code": "27", "name": "Eure", "region": "Normandie", "lat": 49.0833, "lon": 1.0},
    {"code": "28", "name": "Eure-et-Loir", "region": "Centre-Val de Loire", "lat": 48.45, "lon": 1.25},
    {"code": "29", "name": "Finistère", "region": "Bretagne", "lat": 48.25, "lon": -4.0},
    {"code": "30", "name": "Gard", "region": "Occitanie", "lat": 43.9167, "lon": 4.1667},
    {"code": "31", "name": "Haute-Garonne", "region": "Occitanie", "lat": 43.4167, "lon": 1.5},
    {"code": "32", "name": "Gers", "region": "Occitanie", "lat": 43.75, "lon": 0.5833},
    {"code": "33", "name": "Gironde", "region": "Nouvelle-Aquitaine", "lat": 44.85, "lon": -0.5},
    {"code": "34", "name": "Hérault", "region": "Occitanie", "lat": 43.6667, "lon": 3.5},
    {"code": "35", "name": "Ille-et-Vilaine", "region": "Bretagne", "lat": 48.25, "lon": -1.5},
    {"code": "36", "name": "Indre", "region": "Centre-Val de Loire", "lat": 46.75, "lon": 1.5},
    {"code": "37", "name": "Indre-et-Loire", "region": "Centre-Val de Loire", "lat": 47.3333, "lon": 0.75},
    {"code": "38", "name": "Isère", "region": "Auvergne-Rhône-Alpes", "lat": 45.25, "lon": 5.75},
    {"code": "39", "name": "Jura", "region": "Bourgogne-Franche-Comté", "lat": 46.75, "lon": 5.75},
    {"code": "40", "name": "Landes", "region": "Nouvelle-Aquitaine", "lat": 43.9, "lon": -0.9},
    {"code": "41", "name": "Loir-et-Cher", "region": "Centre-Val de Loire", "lat": 47.6, "lon": 1.4},
    {"code": "42", "name": "Loire", "region": "Auvergne-Rhône-Alpes", "lat": 45.7167, "lon": 4.15},
    {"code": "43", "name": "Haute-Loire", "region": "Auvergne-Rhône-Alpes", "lat": 45.0833, "lon": 3.9167},
    {"code": "44", "name": "Loire-Atlantique", "region": "Pays de la Loire", "lat": 47.3, "lon": -1.7},
    {"code": "45", "name": "Loiret", "region": "Centre-Val de Loire", "lat": 47.9167, "lon": 2.0},
    {"code": "46", "name": "Lot", "region": "Occitanie", "lat": 44.6667, "lon": 1.6667},
    {"code": "47", "name": "Lot-et-Garonne", "region": "Nouvelle-Aquitaine", "lat": 44.4167, "lon": 0.5},
    {"code": "48", "name": "Lozère", "region": "Occitanie", "lat": 44.5, "lon": 3.5},
    {"code": "49", "name": "Maine-et-Loire", "region": "Pays de la Loire", "lat": 47.3, "lon": -0.5},
    {"code": "50", "name": "Manche", "region": "Normandie", "lat": 49.0, "lon": -1.25},
    {"code": "51", "name": "Marne", "region": "Grand Est", "lat": 49.0, "lon": 4.25},
    {"code": "52", "name": "Haute-Marne", "region": "Grand Est", "lat": 48.0833, "lon": 5.0},
    {"code": "53", "name": "Mayenne", "region": "Pays de la Loire", "lat": 48.2, "lon": -0.6},
    {"code": "54", "name": "Meurthe-et-Moselle", "region": "Grand Est", "lat": 48.8333, "lon": 6.25},
    {"code": "55", "name": "Meuse", "region": "Grand Est", "lat": 49.0, "lon": 5.3667},
    {"code": "56", "name": "Morbihan", "region": "Bretagne", "lat": 47.75, "lon": -2.75},
    {"code": "57", "name": "Moselle", "region": "Grand Est", "lat": 49.0, "lon": 6.5},
    {"code": "58", "name": "Nièvre", "region": "Bourgogne-Franche-Comté", "lat": 47.1667, "lon": 3.5},
    {"code": "59", "name": "Nord", "region": "Hauts-de-France", "lat": 50.5, "lon": 3.3},
    {"code": "60", "name": "Oise", "region": "Hauts-de-France", "lat": 49.45, "lon": 2.45},
    {"code": "61", "name": "Orne", "region": "Normandie", "lat": 48.6667, "lon": -0.25},
    {"code": "62", "name": "Pas-de-Calais", "region": "Hauts-de-France", "lat": 50.5, "lon": 2.5},
    {"code": "63", "name": "Puy-de-Dôme", "region": "Auvergne-Rhône-Alpes", "lat": 45.75, "lon": 3.0},
    {"code": "64", "name": "Pyrénées-Atlantiques", "region": "Nouvelle-Aquitaine", "lat": 43.25, "lon": -0.5},
    {"code": "65", "name": "Hautes-Pyrénées", "region": "Occitanie", "lat": 43.0833, "lon": 0.1667},
    {"code": "66", "name": "Pyrénées-Orientales", "region": "Occitanie", "lat": 42.6, "lon": 2.5},
    {"code": "67", "name": "Bas-Rhin", "region": "Grand Est", "lat": 48.7, "lon": 7.5},
    {"code": "68", "name": "Haut-Rhin", "region": "Grand Est", "lat": 47.8, "lon": 7.25},
    {"code": "69", "name": "Rhône", "region": "Auvergne-Rhône-Alpes", "lat": 45.8, "lon": 4.6},
    {"code": "70", "name": "Haute-Saône", "region": "Bourgogne-Franche-Comté", "lat": 47.6667, "lon": 6.25},
    {"code": "71", "name": "Saône-et-Loire", "region": "Bourgogne-Franche-Comté", "lat": 46.6667, "lon": 4.5},
    {"code": "72", "name": "Sarthe", "region": "Pays de la Loire", "lat": 47.9, "lon": 0.2},
    {"code": "73", "name": "Savoie", "region": "Auvergne-Rhône-Alpes", "lat": 45.5, "lon": 6.3333},
    {"code": "74", "name": "Haute-Savoie", "region": "Auvergne-Rhône-Alpes", "lat": 46.0, "lon": 6.5},
    {"code": "75", "name": "Paris", "region": "Île-de-France", "lat": 48.8566, "lon": 2.3522},
    {"code": "76", "name": "Seine-Maritime", "region": "Normandie", "lat": 49.7, "lon": 0.9},
    {"code": "77", "name": "Seine-et-Marne", "region": "Île-de-France", "lat": 48.6, "lon": 2.9},
    {"code": "78", "name": "Yvelines", "region": "Île-de-France", "lat": 48.8, "lon": 1.8},
    {"code": "79", "name": "Deux-Sèvres", "region": "Nouvelle-Aquitaine", "lat": 46.5, "lon": -0.4},
    {"code": "80", "name": "Somme", "region": "Hauts-de-France", "lat": 49.9, "lon": 2.3},
    {"code": "81", "name": "Tarn", "region": "Occitanie", "lat": 43.9, "lon": 2.15},
    {"code": "82", "name": "Tarn-et-Garonne", "region": "Occitanie", "lat": 44.0833, "lon": 1.25},
    {"code": "83", "name": "Var", "region": "Provence-Alpes-Côte d'Azur", "lat": 43.4, "lon": 6.3},
    {"code": "84", "name": "Vaucluse", "region": "Provence-Alpes-Côte d'Azur", "lat": 44.0, "lon": 5.2},
    {"code": "85", "name": "Vendée", "region": "Pays de la Loire", "lat": 46.7, "lon": -1.5},
    {"code": "86", "name": "Vienne", "region": "Nouvelle-Aquitaine", "lat": 46.5833, "lon": 0.5},
    {"code": "87", "name": "Haute-Vienne", "region": "Nouvelle-Aquitaine", "lat": 45.9, "lon": 1.3},
    {"code": "88", "name": "Vosges", "region": "Grand Est", "lat": 48.1667, "lon": 6.4},
    {"code": "89", "name": "Yonne", "region": "Bourgogne-Franche-Comté", "lat": 47.8, "lon": 3.6},
    {"code": "90", "name": "Territoire de Belfort", "region": "Bourgogne-Franche-Comté", "lat": 47.6333, "lon": 6.9},
    {"code": "91", "name": "Essonne", "region": "Île-de-France", "lat": 48.5, "lon": 2.25},
    {"code": "92", "name": "Hauts-de-Seine", "region": "Île-de-France", "lat": 48.8333, "lon": 2.25},
    {"code": "93", "name": "Seine-Saint-Denis", "region": "Île-de-France", "lat": 48.9, "lon": 2.45},
    {"code": "94", "name": "Val-de-Marne", "region": "Île-de-France", "lat": 48.8, "lon": 2.45},
    {"code": "95", "name": "Val-d'Oise", "region": "Île-de-France", "lat": 49.1, "lon": 2.2},
    {"code": "971", "name": "Guadeloupe", "region": "Guadeloupe", "lat": 16.25, "lon": -61.5833},
    {"code": "972", "name": "Martinique", "region": "Martinique", "lat": 14.6667, "lon": -61.0},
    {"code": "973", "name": "Guyane", "region": "Guyane", "lat": 4.0, "lon": -53.0},
    {"code": "974", "name": "La Réunion", "region": "La Réunion", "lat": -21.1, "lon": 55.5},
    {"code": "976", "name": "Mayotte", "region": "Mayotte", "lat": -12.8, "lon": 45.15},
]


